App.MvcWebUI/Models/CartListViewModel.cs
using App.Entities.Concrete;

namespace App.MvcWebUI
{
    public class CartListViewModel
    {
        public Cart Cart { get; internal set; }
    }
}

App.MvcWebUI/Models/CartSummaryViewModel.cs
using App.Entities.Concrete;

namespace App.MvcWebUI
{
    public class CartSummaryViewModel
    {
        public Cart Cart { get; set; }
    }
}

App.MvcWebUI/Models/CategoryListViewModel.cs
using App.Entities.Concrete;

namespace App.MvcWebUI
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; internal set; }
    }
}

App.MvcWebUI/Models/ErrorViewModel.cs
namespace App.MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

App.MvcWebUI/Models/ProductListViewModel.cs
using App.Entities.Concrete;

namespace App.MvcWebUI
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
        public int PageCount { get; set; }
        public int PageSize { get; set; }
        public int CurrentCategory { get; set; }
        public int CurrentPage { get; set; }
        public string Order { get; set; }
    }
}

App.MvcWebUI/Controllers/CartController.cs
using App.Business.Abstract;
using App.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;

namespace App.MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartSessionService _cartSessionService;
        private ICartService _cartService;
        private IProductService _productService;

        public CartController(ICartSessionService cartSessionService, ICartService cartService, IProductService productService)
        {
            _cartSessionService = cartSessionService;
            _cartService = cartService;
            _productService = productService;
        }


        public IActionResult AddToCart(int productId)
        {
            var productToBeAdded=_productService.GetById(productId);

            var cart = _cartSessionService.GetCart();

            _cartService.AddToCart(cart, productToBeAdded);

            _cartSessionService.SetCart(cart);

            TempData.Add("message", String.Format("Your product, {0} was added successfully to cart!", productToBeAdded.ProductName));

            return RedirectToAction("Index", "Product");
        }


        public IActionResult List()
        {
            var cart=_cartSessionService.GetCart();
            CartListViewModel cartListViewModel = new CartListViewModel
            {
                Cart = cart
            };
            return View(cartListViewModel);
        }

        public IActionResult Remove(int productId)
        {
            var cart = _cartSessionService.GetCart();

            _cartService.RemoveFromCart(cart, productId);
            _cartSessionService.SetCart(cart);
            TempData.Add("message", "Your Product , {0} was removed successfully from cart!");

            return RedirectToAction("List");
        }
    }
}

App.MvcWebUI/Controllers/HomeController.cs
using App.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace App.MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

App.MvcWebUI/Controllers/ProductController.cs
using App.Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace App.MvcWebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int page = 1, int category = 0, string order = "AtoZ")
        {
            int pageSize = 10;
            var products = String.IsNullOrEmpty(category.ToString()) ?
                            _productService.GetAll() :
                            _productService.GetByCategory(category);


            switch (order)
            {
                case "AtoZ":
                    products = _productService.GetByAtoZ(products);
                    break;
                case "ZtoA":
                    products = _productService.GetByZtoA(products);
                    break;
                case "PriceLtoH":
                    products = _productService.GetByPriceLtoH(products);
                    break;
                case "PriceHtoL":
                    products = _productService.GetByPriceHtoL(products);
                    break;
            }

            var model = new ProductListViewModel
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = category,
                CurrentPage = page,
                Order = order
            };
            return View(model);
        }


    }
}

App.MvcWebUI/ViewComponents/CartSummaryViewComponent.cs
using App.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace App.MvcWebUI.ViewComponents
{
    public class CartSummaryViewComponent:ViewComponent
    {
        private ICartSessionService _cartSessionService;

        public CartSummaryViewComponent(ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
        }
        public ViewViewComponentResult Invoke()
        {
            var model = new CartSummaryViewModel
            {
                Cart = _cartSessionService.GetCart()
            };
            return View(model);
        }
    }
}

App.MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using App.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace App.MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {

            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = String.IsNullOrEmpty(HttpContext.Request.Query["category"]) ? 0 : Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

App.MvcWebUI/Views/Cart/List.cshtml
@model CartListViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2> Your Cart</h2>

<table class="table" >
    <tr>
        <td>Product Name</td>
        <td>Unit Price</td>
        <td>Units In Stock</td>
        <td>Quantity</td>
        <td></td>
    </tr>
    @foreach(var item in Model.Cart.CartLines)
    {
        <tr>
            <td>@item.Product.ProductName</td>
            <td>@item.Product.UnitPrice</td>
            <td>@item.Product.UnitsInStock</td>
            <td>@item.Quantity</td>
            <td class="text-right" ><a class="btn btn-xs btn-danger" asp-controller="Cart" asp-action="Remove"
            asp-route-productId="@item.Product.ProductId"
            >Remove from cart</a></td>
        </tr>
    }
    <tr>
       <td></td>
       <td></td>
       <td></td>
       <td>
           <h3>Total</h3>
       </td>
       <td class="text-right" >
           <h3>
               <strong>@Model.Cart.Total  $</strong>
           </h3>
       </td>
   </tr>
   <tr>
       <td></td>
       <td></td>
       <td></td>
       <td >
           <a asp-controller="Product" asp-action="Index" class="btn btn-xs btn-default">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg> Continue Shopping</a>
       </td>
       <td class="text-right">
            <a asp-controller="Cart" asp-action="Complete" class="btn btn-xs btn-default">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg> Go to checkout</a>
       </td>

   </tr>
</table>

App.MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

App.MvcWebUI/Views/Product/Index.cshtml
@model ProductListViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               ProductName
            </th>

            <th>
                UnitPrice
            </th>
            <th>
                UnitsInStock
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
            
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitsInStock)
                </td>
                <td>
                    <a class="btn btn-xs btn-success" asp-action="AddToCart" asp-controller="Cart"  asp-route-productId="@item.ProductId">Add To Cart</a> 
                 @*   <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

<product-list-pager
current-category="@Model.CurrentCategory"
current-page="@Model.CurrentPage"
page-count="@Model.PageCount"
page-size="@Model.PageSize"
order="@Model.Order"
>

</product-list-pager>

App.MvcWebUI/Views/Shared/Components/CartSummary/Default.cshtml
@model CartSummaryViewModel


<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li>
        <ul class="list-group">

            @foreach (var item in Model.Cart.CartLines)
            {
                <li class="list-group-item">
                    <a> @item.Product.ProductName <span class="badge bg-success p-2 rounded text-white">@item.Quantity</span> </a>
                </li>
            }
        </ul>
    </li>



    <li class="dropdown-divider"></li>

    <li class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.Cart.Total $</h5>
            <a class="btn btn-primary" asp-controller="Cart" asp-action="List">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
                Go to cart details
            </a>
        </div>
    </li>



</ul>

App.MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<div class="list-group" >
    @foreach(var item in Model.Categories)
    {
        var css = "list-group-item";
        if (Model.CurrentCategory == item.CategoryId)
        {
            css += " active";
        }
        <a href="/product/index?category=@item.CategoryId" class="@css" >@item.CategoryName</a>
    }
</div>

App.MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - App.MvcWebUI</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet"
		  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<div>
		<nav class="navbar navbar-expand-lg navbar-light bg-light p-3">
			<a class="navbar-brand" href="/product/index">E-Commerce</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent" style="justify-content: space-between">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/product/index">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/account/login">Admin</a>
					</li>
				</ul>

				<ul class="nav navbar-nav" style="margin-right:200px">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
								<path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
							</svg> Cart
						</a>
						@await Component.InvokeAsync("CartSummary")
					</li>

				</ul>
			</div>
		</nav>
	</div>

	<div class="row mr-0">
		<div class="col-md-2">
			@await Component.InvokeAsync("CategoryList")
		</div>
		<div class="col-md-10">
			@{
				// Path  duzeldirem, asaqidaki optionlardan hansinin value - a 
				// beraber olsa o selected olmus olacaq
				var selecteditem = "\\product?order=" + @Context.Request.Query["order"] + "&category=" + @Context.Request.Query["category"];
			}
			<select asp-for="@selecteditem" onchange="location=this.value" aria-label="Default select example" class="form-select  w-25">
				<option value="\product?order=AtoZ&category=@Context.Request.Query["category"]">A->Z</option>
				<option value="\product?order=ZtoA&category=@Context.Request.Query["category"]">Z->A</option>
				<option value="\product?order=PriceLtoH&category=@Context.Request.Query["category"]">Price Low->High</option>
				<option value="\product?order=PriceHtoL&category=@Context.Request.Query["category"]">Price High->Low</option>
			</select>
			@if (TempData["message"] != null)
			{
				<div class="alert alert-info animate__animated animate__backInLeft" role="alert">@TempData["message"]</div>
			}
			@RenderBody()
		</div>
	</div>


	<div class="col-md-12">Footer</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>